### ISSUE TITLE
Mehrere Termine pro Woche

### ISSUE THREAD

**Issue by domwass** [jspitz/jslectureplanner#2]
Lieber Jürgen,
gleich noch ein weiteres Problem, dass sich mir stellt. Es gibt bei uns Kurse, die zwei Termine in der Woche haben. Das lässt sich derzeit bei der Erstellung des Programms nicht einstellen, soweit ich das sehe. Man müsste vielleicht zwei Intervalle angeben können, so dass der Zähler zunächst z.B. zwei Tage hochrechnet und dann noch einmal fünf Tage. Das ist aber nur eine erste Idee, vielleicht fällt Dir eine bessere und elegantere Lösung ein.
Beste Grüße,
Dominik.-

**Comment by jspitz** [comment]
Zwei Termine heißt bspw. immer dienstags und donnerstags?

Das würde momentan so gehen:

\LecInterval{2}% setzt das generelle Intervall auf 2 Tage

und dann nach jeweils der zweiten Sitzung der Woche:

\SetLecOffset{3}% verschiebt alle folgenden Sitzungen um 3 Tage (3+2 = 5)

Oder nicht?

Das ist nicht ideal, ich weiß, aber über ein besseres UI müsste ich noch nachdenken.

**Comment by domwass** [comment]
Ja, das funktioniert, vielen Dank.

**Comment by jspitz** [comment]
I have now added a macro
\SetAutoOffset{after x sessions}{shift by y days}

Thus, you now only need once
\LecInterval{2}
\SetAutoOffset{2}{3}

Again, please test.

**Comment by domwass** [comment]
This is much more convenient, thank you!
According to a brief test everything seems to work.

**Comment by jspitz** [comment]
V. 1.0 is approaching CTAN.
