### ISSUE TITLE
Neue Makros: \lecturer und \office

### ISSUE THREAD

**Issue by domwass** [jspitz/jslectureplanner#3]
Lieber Jürgen,
es wäre schön, wenn man auch den (oder die) Veranstalter bzw. Dozenten eines Kurses sowie das Büro angeben könnte. Ersteres ist nützlich beim Ausgeben von Kursmaterial, letzteres würde man in Kombination mit `\officehours` nutzen können. Ich schlage dafür die Markos `\lecturer` und `\office` vor.
Gruß,
Dominik.-

**Comment by jspitz** [comment]
Lieber Dominik
Ersteres gibt es in der Entwicklerversion (hier auf github) schon: \LecInstructor und "instructor"-Option für einzelne Sessions. Schau mal, ob das das ist, was du meinst.

Office ist eine gute Idee. Du meinst hier aber nur global (für den ganzen Kurs), oder?

**Comment by jspitz** [comment]
The office number can be recorded on a global level now (via \SetOfficeNumber and the "officenumner" package option; the macro \officenumber holds the value)

(I did not use "office" since I fear this clashes with other packages)

Dominik, could you please test the dev version?

**Comment by domwass** [comment]
Both `\lecinstructor` and `\officenumber` work perfectly here.
Thanks a lot,
Dominik.-

**Comment by domwass** [comment]
Ach so, die Angabe zum Büro meinte ich für den ganzen Kurs, ja (damit die Studierenden auch wissen, wo sie mich zur Sprechstundenzeit finden …).

**Comment by jspitz** [comment]
V. 1.0 is approaching CTAN.
