### ISSUE TITLE
Wrong encoding on jlectureplanner.tex

### ISSUE THREAD

**Issue by rzach** [jspitz/jslectureplanner#5]
I think `jslectureplanner.tex` is saved in the wrong character encoding. When I clone this and compile it, it produces *Jï¿œrgen Spitzmï¿œller* instead of *Jürgen Spitzmüller* as the author.

**Comment by rzach** [comment]
I guess that happens because my editor expects things to be UTF8 encoded. I imported the repository into Overleaf and it also screwed up the ü. It seems to me that UTF8 is pretty much standard now, so switch over or replace with \"u and avoid the problem altogether?

**Comment by jspitz** [comment]
Right, thanks.
